SWC-6121
Sage-Bionetworks/Synapse-React-Client pull request #1592
Opened 2022-06-14 17:35 UTC by yjyoo773

2022-06-15 19:47 UTC, yjyoo773 commented
<img width="1257" alt="Screen Shot 2022-06-15 at 12 46 18 PM" src="https://user-images.githubusercontent.com/60489495/173913589-a57633dd-3b25-4995-9747-31e3aff747aa.png">
<img width="1229" alt="Screen Shot 2022-06-15 at 12 47 01 PM" src="https://user-images.githubusercontent.com/60489495/173913604-e1462b66-c01e-43be-9e62-8762839065cc.png">

2022-06-15 21:04 UTC, nickgros requested changes

2022-06-15 21:41 UTC, yjyoo773 commented on src/lib/containers/dataaccess/AccessHistoryDashboard.tsx
> +          />
I agree applying the change for "Requester" in the SubmissionDashboard since it filters based on the individual user name rather than a team name

2022-06-16 13:57 UTC, nickgros approved these changes
Looks great--see comment for one last change before merging

2022-06-16 17:33 UTC, merged